bitrate = 320
default_keybindings = true

[keybindings]
"F8" = "noop"
"." = "noop"
"p" = "noop"
"d" = "noop"
"Shift+p" = "noop"
"Shift+s" = "noop"
"f" = "noop"
"Shift+f" = "noop"
"b" = "noop"
"Shift+b" = "noop"
"z" = "noop"
"Shift+a" = "noop"
"m" = "noop"
"Shift+m" = "noop"
"Backspace" = "noop"
"Shift+x" = "noop"
"Ctrl+s" = "noop"
"?" = "help"
"Enter" = "play"
"Space" = "playpause"
"Right" = "seek +5s"
"Left" = "seek -5s"
"h" = "move left"
"j" = "move down"
"k" = "move up"
"l" = "move right"
"Ctrl+u" = "move pageup 0.5"
"Ctrl+d" = "move pagedown 0.5"
"o" = "open selected"
"Esc" = "back"
"r" = "repeat"
"s" = "shuffle"
"<" = "previous"
">" = "next"
"F1" = "focus search"
"F2" = "focus queue"
"F3" = "focus library"
"F4" = "focus cover"
"c" = "newplaylist newPlayList"
"Ctrl+a" = "add"
"a" = "save"
"Ctrl+x" = "delete"
"Ctrl+q" = "quit"
